name=input("Enter your name:")

ans=name.upper()
print(ans)
ans=name.lower()
print(ans)
print(name.title())
print(name.capitalize())
print(name.count("private"))
print(name.find("a"))
print(name.index("a"))
print(name.endswith("a"))
print(name.startswith("a"))
print(name.strip("a"))
